Fix Syntax Highlighting
Nordgedanken/auto_hot_key_jetbrains_plugin pull request #36
Opened 2021-01-24 22:50 UTC by takanuva15

Hey, I know it's been some time but I finally got around to exploring the bnf/jflex code to try and fix it. 

Basically I removed all the classes that were causing errors and I commented out the original bnf/lex code that was there. In its place, I put a simplified version of the bnf that _only_ checks for line comments currently, and it should give 0 errors for any script that includes line comments (I had to check the rules for line comments in AutoHotkey; the only thing missing here is support for comments in multiline strings which will be fixed later when string bnf is added). I also added some junit tests and modified the github actions .yml file based on your older PR which will run all the tests to verify. 

I also fixed the version compatibility issues with IDEA 2020, so you should be able to publish a new version of the plugin after this PR (v4.0.0). (I was forced to drop support for IDEA 2019 because JetBrains changed some of the APIs significantly). In the next PR, I will add support for block comments and a GitHub action to check the test coverage.

2021-01-25 02:56 UTC, takanuva15 commented
Hmm the build looks stuck since the github yaml file was updated. Seems this has been reported before; something might need to be updated in the repository settings. See here as example: https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157/5

2021-01-25 10:49 UTC, MTRNord commented
> 
> 
> Hmm the build looks stuck since the github yaml file was updated. Looks like the build checks or something might need to be updated in the repository branch settings. (Seems this has been reported before, see [here](https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157/5) for example: )
> 
> ![image](https://user-images.githubusercontent.com/6986426/105656386-15dc6900-5e90-11eb-8db2-ff3a1ed63208.png)

Fixed :)

2021-01-25 10:50 UTC, MTRNord commented
I will review this later today. Also sorry that I did not work on this for a long time. Just didnt get to it since University started,

2021-01-25 12:22 UTC, takanuva15 commented
> I will review this later today. Also sorry that I did not work on this for a long time. Just didnt get to it since University started,

Lol yea, university work always swallowed most of any free time I had while I was at Uni.

2021-01-26 21:32 UTC, MTRNord requested changes
Looks fine except the commented stuff which just can be removed. We always are able to go back in the git history

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/ide/highlighter/AhkColors.kt
> +//    FUNCTION("Functions//Function declaration", DefaultLanguageHighlighterColors.FUNCTION_DECLARATION),
Just remove the commented lines. Thats the beauty of version control. No need to keep them. We can always look at old commits

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/ide/highlighter/AhkHighlightAnnotator.kt
> +//        if (psiElem is AhkHotkeyAssignment) {
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/ide/highlighter/AhkSyntaxHighlighter.kt
> +//            HOTKEY_ASSIGNMENT -> AhkColor.FUNCTION
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/lang/lexer/AutoHotkey.flex
> +//language-specific
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/lang/lexer/AutoHotkey.flex
> +/*
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/lang/parser/AhkParserDefinition.kt
> +/*    override fun spaceExistanceTypeBetweenTokens(left: ASTNode, right: ASTNode): ParserDefinition.SpaceRequirements {
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/lang/parser/AutoHotkey.bnf
> +//Hotkey ::= ('#'|'!'|'^'|'+'|'<'|'>'|'<^>!'|'*'|'~'|'$')* (id | CHAR_SPECIAL) (WHITESPACE '&' WHITESPACE (id | CHAR_SPECIAL))? (WHITESPACE 'Up')? { rightAssociative=true}
Same as above

2021-01-26 21:32 UTC, MTRNord commented on src/main/java/de/nordgedanken/auto_hotkey/lang/psi/AhkTokenType.kt
> +//val AHK_ITEMS = tokenSetOf(
Same as above

2021-01-27 22:54 UTC, MTRNord approved these changes
Looks fine :) Feel free to press merge if you are ready to merge this. (Not sure if this is WIP or ready? :D)

2021-01-27 22:55 UTC, MTRNord commented
Oh I apparently went really strict with checks... Lets loosen that up :3

2021-01-27 23:07 UTC, takanuva15 commented
> Looks fine :) Feel free to press merge if you are ready to merge this. (Not sure if this is WIP or ready? :D)

I don't see any 'Merge' button... I think only you have write access to this repository so you would have to merge the PR. 
(This is ready to merge; I would just make a 'draft pull request' or add a comment if I wasn't ready to merge yet)

2021-01-27 23:11 UTC, MTRNord commented
> > Looks fine :) Feel free to press merge if you are ready to merge this. (Not sure if this is WIP or ready? :D)
> 
> I don't see any 'Merge' button... I think only you have write access to this repository so you would have to merge the PR.
> (This is ready to merge; I would just make a 'draft pull request' or add a comment if I wasn't ready to merge yet)

Ah thought you were allowed to merge things :)

2021-01-27 23:11 UTC, merged

2021-01-27 23:12 UTC, MTRNord commented
Will need to see when I am able to do another release :) (If I dont do it until something like next week friday feel free to give me a ping here :) I try to not forget)